apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storagebuckets.platform.example.com
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: StorageBucket
  mode: Pipeline
  pipeline:
  - functionRef:
      name: uchris-project-ack-aws-s3compose-bucket-kcl
    step: compose-bucket-kcl
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
