apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: storagebuckets.platform.example.com
spec:
  group: platform.example.com
  names:
    categories:
    - crossplane
    kind: StorageBucket
    plural: storagebuckets
  scope: Namespaced
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: StorageBucket is the Schema for the StorageBucket API.
        properties:
          spec:
            description: StorageBucketSpec defines the desired state of StorageBucket.
            properties:
              parameters:
                properties:
                  region:
                    description: Region specifies the AWS region where the S3 bucket will be created.
                    type: string
                    default: "us-west-1"
                  versioning:
                    description: Versioning indicates whether versioning is enabled for the S3 bucket. When enabled, multiple versions of an object are kept in the bucket.
                    type: boolean
                type: object
                required:
                - region
                - versioning
            type: object
            required:
            - parameters
          status:
            description: StorageBucketStatus defines the observed state of StorageBucket.
            type: object
        required:
        - spec
        type: object
    served: true
